package me.yesd.World.Objects.Animals;

public enum AnimalType {
    NULL(Animal.class),
    MOUSE(Animal.class),
    RABBIT(Animal.class),
    PIG(Animal.class),
    FOX(Animal.class),
    DEER(Animal.class),
    MOLE(Animal.class),
    ZEBRA(Animal.class),
    LION(Animal.class),
    BIGCAT(Animal.class),
    BEAR(Animal.class),
    CROC(Animal.class),
    RHINO(Animal.class),
    HIPPO(Animal.class),
    DRAGON(Animal.class),
    SHRIMP(Animal.class),
    TROUT(Animal.class),
    CRAB(Animal.class),
    SQUID(Animal.class),
    SHARK(Animal.class),
    STINGRAY(Animal.class),
    TURTLE(Animal.class),
    SEAHORSE(Animal.class),
    JELLYFISH(Animal.class),
    KRAKEN(Animal.class),
    PUFFERFISH(Animal.class),
    KILLERWHALE(Animal.class),
    SWORDFISH(Animal.class),
    GORILLA(Animal.class),
    OCTOPUS(Animal.class),
    WOLF(Animal.class),
    ARCTICHARE(Animal.class),
    YETI(Animal.class),
    CHIPMUNK(Animal.class),
    MUSKOX(Animal.class),
    PENGUIN(Animal.class),
    POLARBEAR(Animal.class),
    SEAL(Animal.class),
    SNOWLEOPARD(Animal.class),
    WALRUS(Animal.class),
    REINDEER(Animal.class),
    ARCTICFOX(Animal.class),
    WOLVERINE(Animal.class),
    MAMMOTH(Animal.class),
    DONKEY(Animal.class),
    SNAIL(Animal.class),
    BLACKDRAGON(Animal.class),
    SABERTOOTHTIGER(Animal.class),
    ELEPHANT(Animal.class),
    BLUEWHALE(Animal.class),
    COBRA(Animal.class),
    BOACONSTRICTOR(Animal.class),
    GIANTSPIDER(Animal.class),
    TREX(Animal.class),
    TIGER(Animal.class),
    GIRAFFE(Animal.class),
    EAGLE(Animal.class),
    HEDGEHOG(Animal.class),
    DUCK(Animal.class),
    DUCKLING(Animal.class),
    LEMMING(Animal.class),
    KINGCRAB(Animal.class),
    FROG(Animal.class),
    OSTRICH(Animal.class),
    PELICAN(Animal.class),
    FALCON(Animal.class),
    SNOWYOWL(Animal.class),
    HONEYBEE(Animal.class),
    PHOENIX(Animal.class),
    OSTRICHBABY(Animal.class),
    SEAMONSTER(Animal.class),
    LANDMONSTER(Animal.class),
    ICEMONSTER(Animal.class),
    DINOMONSTER(Animal.class),
    PIGEON(Animal.class),
    TOUCAN(Animal.class),
    MACAW(Animal.class),
    FLAMINGO(Animal.class),
    CASSOWARY(Animal.class),
    CHICKEN(Animal.class),
    WOODPECKER(Animal.class),
    PEACOCK(Animal.class),
    KANGAROORAT(Animal.class),
    DESERTCHIPMUNK(Animal.class),
    MEERKAT(Animal.class),
    GAZELLE(Animal.class),
    ARMADILLO(Animal.class),
    FENNECFOX(Animal.class),
    CAMEL(Animal.class),
    WARTHOG(Animal.class),
    HYENA(Animal.class),
    RATTLESNAKE(Animal.class),
    VULTURE(Animal.class),
    BISON(Animal.class),
    KOMODODRAGON(Animal.class),
    GIANTSCORPION(Animal.class),
    PTERODACTYL(Animal.class),
    GOBIBEAR(Animal.class),
    BLACKWIDOW(Animal.class),
    BULLETANT(Animal.class),
    KINGDRAGON(Animal.class),
    SNOWMAN(Animal.class),
    SANTA(Animal.class),
    RUDOLPH(Animal.class),
    DEATHWORM(Animal.class),
    MARKHOR(Animal.class),
    BIGFOOT(Animal.class),
    AIBOSS(Animal.class),
    RAVEN(Animal.class),
    KAKAPO(Animal.class),
    PHEASANT(Animal.class),
    WHITEGIRAFFE(Animal.class),
    TURKEY(Animal.class),
    SANDSTORM(Animal.class),
    DRAGONFIRE(Animal.class);

    private Class animalClass;

    AnimalType(Class animalClass) {
        this.animalClass = animalClass;
    }

    public Class getAnimalClass() {
        return animalClass;
    }

    public boolean hasCustomClass() {
        return animalClass != Animal.class;
    }
}
